using System;
using System.Configuration;
using System.IO;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.WindowsAzure.Storage;
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using ImageResizer;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.WindowsAzure.Storage.Blob;
using ServerlessDemo.Integrations.Functions.Infrastructure;

namespace ServerlessDemo.Integrations.Functions
{
    public static class GenerateThumbnail
    {
        [FunctionName("GenerateThumbnail")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            var inputStream = await req.Content.ReadAsStreamAsync();
            log.Info("START");
            byte[] bytes;

            // Generate a thumbnail and save it in the "thumbnails" container
            using (var outputStream = new MemoryStream())
            {
                var settings = new ResizeSettings { MaxWidth = 192, Format = "png" };
                ImageBuilder.Current.Build(inputStream, outputStream, settings);
                outputStream.Seek(0L, SeekOrigin.Begin);
                bytes = outputStream.ToArray();
            }

            log.Info("Generated bytes");
            
            var response = new ResponseModel()
            {
                Bytes = bytes
            };
            return req.CreateResponse(response);
        }

        public class ResponseModel
        {
            public byte[] Bytes { get; set; }
        }
    }
}
